<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\CatalogInventory\Block\Qtyincrements
 */
?>
<?php if ($block->getProductQtyIncrements()) : ?>
    <div class="product pricing qtyincrements">
        <?= $block->escapeHtml(__('%1 is available to buy in increments of %2', "This product", $block->getProductQtyIncrements())) ?>
    </div>
<?php endif ?>
