<?php
/**
 * Copyright © Mageside. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */
?>
<div class="mageside-hint">
    <img src="https://mageside.com/skin/frontend/rwd/mageside_shop/images/logo.png"/><br><br>
    <div class="content">
        <p>
            <strong class="module-name">
                <?php echo $block->escapeHtml($block->getModuleName()) ?> <?php echo $block->escapeHtml($block->getVersion()) ?>
            </strong>
            <?php echo $block->escapeHtml(__(' by')) ?>
            <a target="_blank" href="https://mageside.com/">
                <strong>Mageside</strong>
            </a>
        </p>
        <p>
            <?php echo $block->escapeHtml(__('Your feedback for ')) ?>
            <a href="<?php echo $block->escapeHtml($block->getModulePage()) ?>" target="_blank"><?php echo $block->escapeHtml($block->getModuleName()) ?></a>
            <?php echo $block->escapeHtml(__('is highly appreciated.')) ?>
        </p>
        <p>
            <?php echo $block->escapeHtml(__('Found an issue? Need help? Got custom request? Please ')) ?>
            <a href="https://mageside.com/contacts/" target="_blank"><?php echo $block->escapeHtml(__('Contact us')) ?></a>.
        </p>
        <p>
            <?php echo $block->escapeHtml(__('You can check more extensions designed by our team on ')) ?>
            <a href="https://marketplace.magento.com/partner/Mageside" target="_blank"><?php echo $block->escapeHtml(__('Magento Marketplace')) ?></a>.
        </p>
    </div>
</div>
