<?php
/**
 * Copyright © Mageside. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */
/**
 * @var $block \Mageside\Recipe\Block\Frontend\Recipe\RecipeList
 */
$config = $this->helper(\Mageside\Recipe\Helper\Config::class);
?>
<?php if ($config->getShowOnProductPage()) : ?>
    <?php if ($block->getCollectionSize()) : ?>
        <strong><?php echo $config->getProductBlockTitle(); ?></strong>
        <div class="recipe-list-wrapper">
            <ul class="recipe-grid">
                <?php echo $block->getChildHtml('recipe_list'); ?>
            </ul>
        </div>
        <div class="recipe-list-wrapper" style="justify-content: center">
            <div class="more-recipes" style="text-align: center">
                <button id="update-recipes" class="action tocart primary action-allcart-primary">
                    <span class="label"><?php echo $block->escapeHtml(__('See more recipes')); ?></span>
                </button>
            </div>
        </div>
        <script type="text/x-magento-init">
        {
            "#update-recipes": {
                "Mageside_Recipe/js/load-recipes-list": {
                    "productId": "<?php /* @escapeNotVerified */ echo $block->getProductId(); ?>",
                    "itemsPerPage": "<?php /* @escapeNotVerified */ echo $config->getRecipesPerProductPage() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>