<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
?>
<script type="text/javascript">
    var QUICKVIEW_BASE_URL = '<?php echo $baseUrl; ?>';


	
    //alert("Page loaded.");
	 require(['jquery', 'jquery/ui'], function($){ 

jQuery( document ).ready(function() {

var head = jQuery(".mfp-iframe").contents().find("head");
var css = '<style type="text/css">' +
          '#maincontent{display:none}; ' +
          '</style>';
jQuery(head).append(css);

	
});
});	


</script>
