<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product = $block->getProduct();
$qtyInc = $_product->getExtensionAttributes()->getStockItem()->getQtyIncrements();
$defaultQty = $qtyInc ?? $block->getProductDefaultQty() * 1;
?>

<a href="<?php echo $block->getUrl('wishlist', ['_secure' => true]);?>" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><span><?php echo __('Add to Wishlist') ?></span></a>

<?php if ($_product->isSaleable()): ?>

	<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
	
	<?php // If is deals product. Show countdown time ?>
	<?php if($_product->getSpecialPrice() && $_product->getSpecialToDate() && $_product->getSpecialFromDate()): ?>
		
		<?php $dateTimeFormat = \Magento\Framework\Stdlib\DateTime::DATETIME_PHP_FORMAT; ?>
		<?php $now = $themeHelper->getCurrentDateTime(); ?>
		<?php $specialFromDate = date($dateTimeFormat, strtotime($_product->getSpecialFromDate())); ?>
		<?php $specialToDate = date($dateTimeFormat, strtotime($_product->getSpecialToDate())); ?>
		
		<?php if($specialFromDate <= $now && $specialToDate > $now): ?>
			<div class="product-detail-deals margin-top25">
				<?php echo $this->getLayout()
                                ->createBlock('Magento\Framework\View\Element\Template')
                                ->setProduct($_product)
                                ->setTimeNow($now)
                                ->setSpecialFromDate($specialFromDate)
                                ->setSpecialToDate($specialToDate)
                                ->setTemplate('MGS_Mpanel::products/deals/countdown.phtml')
                                ->toHtml() ?>
			</div>
		<?php endif ?>
		
	<?php endif ?>
	<?php // End Deals ?>

	<div class="box-tocart">
		<?php echo $block->getChildHtml('', true) ?>

        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <span class="edit-qty minus disable-select-text" onclick="minusQty('qty')">-</span>
            <input type="number"
                   name="qty"
                   id="qty"
                   maxlength="12"
                   value="<?php /* @escapeNotVerified */ echo $defaultQty ?>"
                   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                   readonly
                   />
            <span class="edit-qty plus disable-select-text" onclick="plusQty('qty')">+</span>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo __('Add') ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span class="text"><?php /* @escapeNotVerified */ echo __('Add') ?></span>
            </button>
            <?php
                $_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
                $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
            ?>
        </div>
	</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<?php if ($block->shouldRenderQuantity()): ?>
	<script type="text/javascript">
		function plusQty(qtyInput){
			require([
			'jquery'
			], function(jQuery){
				(function($) {
					if($('#'+qtyInput).attr('disabled')!='disabled'){
						qty = $('#'+qtyInput).attr('value');
						qty = parseInt(qty);
						qty += 1 * <?= $qtyInc ?>;
						$('#'+qtyInput).val(qty);
						$('#sticky_qty').val(qty);
					}
				})(jQuery);
			});
			
		}
		function minusQty(qtyInput){
			require([
			'jquery'
			], function(jQuery){
				(function($) {
					if($('#'+qtyInput).attr('disabled')!='disabled'){
						qty = $('#'+qtyInput).attr('value');
						qty = parseInt(qty);
						
						if(qty>1){
                            qty -= 1 * <?= $qtyInc ?>;
							$('#'+qtyInput).val(qty);
                            $('#sticky_qty').val(qty);
						}
					}
				})(jQuery);
			});
		}
	</script>
<?php endif; ?>


<style type="text/css">
	
.product-social-links .product-addto-links{display: none;}

.mp_social_share_inline{float:left !important;}


</style>