<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>

<?php // Helper ?>
<?php $_imagehelper = $this->getImageHelper(); ?>
<?php $themeHelper = $this->getThemeHelper(); ?>
<?php $quickViewHelper = $this->getQuickViewHelper(); ?>
<?php $_helper = $this->getCatalogHelperOutput(); ?>
<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>

<?php // Product item & attribute ?>
<?php $_product = $this->getProduct(); ?>
<?php $lazyLoad = $this->setLazyLoad(); ?>
<?php $baseImage = $hoverBaseImage = $this->getLazyLoadBaseImage(); ?>
<?php $ratio = $this->getRatio(); ?>
<?php $productUrl = $_product->getProductUrl(); ?>
<?php $change_img = $this->getHoverChange(); ?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $productStockObj = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')
        ->getStockItem($_product->getData('entity_id'));
    $qtyInc = $productStockObj->getQtyIncrements();
    $defaultQty = $qtyInc ?? $block->getProductDefaultQty() * 1;
?>

<?php
    /*$registry = $objectManager = \Magento\Framework\App\ObjectManager::getInstance()
                    ->get('Magento\Framework\Registry');
    $registry->register('current_product', $_product);

    if($registry->registry('current_product')) {

    }*/

    $blockStoreLocator = $this->getLayout()
        ->createBlock('Amasty\Storelocator\Block\Location')
        ->setAltProduct($_product)
        ->setTemplate("Amasty_Storelocator::link_v2.phtml");
?>
<div class="product-item-info" data-container="product-grid">
	<?php // Product Top ?>
	<div class="product-top">
		<?php 
            $size = $this->getSize();
			$productImage = $_imagehelper->init($_product, 'category_page_grid')->resize($size['width'], $size['height'])->getUrl();
            if(!$lazyLoad){
                $baseImage = $productImage;
            }
		?>
		
		<div class="product_review_name_custom">
		<?php // Product Name ?>
			<h5 class="product name product-item-name">
				<a class="product-item-link"
				   href="<?php /* @escapeNotVerified */ echo $productUrl ?>">
					<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
				</a>
			</h5>
		
		
		<?php echo $this->getReview(); ?>
		
		</div>
		
		<a href="<?php echo $productUrl ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $this->getPadding(); ?>;"  tabindex="-1">
        
            <?php $imgAlt = $block->stripTags($_product->getName(), null, true); ?>
            
			<img src="<?php echo $baseImage ?>" alt="<?php echo $imgAlt; ?>" class="img-responsive product-image-photo img-thumbnail<?php if($lazyLoad): ?> lazy<?php endif ?>" data-src="<?php echo $productImage ?>"/>
            
			<div class="product-image-photo"></div>
            
		</a>
		
		<?php // Product Label ?>
		<?php echo $themeHelper->getProductLabel($_product) ?>
		
		<div class="product-detail-action">
            
			<?php // Compare  ?>
			<?php if($this->getCompare()): ?>
				<button class="action tocompare"
				   data-title="<?php echo __('Add to Compare') ?>"
				   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
				   role="button">
					<i class="pe-7s-graph3"></i>
				</button>
			<?php endif ?>
            
			
		
            
			<?php // QuickView  ?>
			<?php echo $quickViewHelper->aroundQuickViewHtml($_product, $ratio); ?>
		</div>
	</div>
	
	<?php // Product Detail ?>

	<div class="product-dietary-requirements">

	<?php
    $data = explode(',',$_product->getData('dietary_requirements'));
	$data = array_unique($data);
    //$top_dietary = [ "DF", "GF", "O", "V+", "V", "WF", "SF", "FT", "R", "PO" ];
    $top_dietary = [ "Dairy Free", "Gluten Free", "Organic", "Raw", "Vegan", "Vegetarian", "Wheat Free", "Sugar Free", "Fair Trade", "Produce of GB" ];
		$count = 0;		
	    foreach($data as $value):    
			if($count > 9) break;        
	    ?>
	        <?php 
	        $attr = $_product->getResource()->getAttribute('dietary_requirements');
	        if ($attr->usesSource()): ?>
	            <?php 
	            $option_value = $attr->getSource()->getOptionText($value);
                if(!in_array($option_value, $top_dietary)) {
                    continue;
                }
				$words = explode(' ', $option_value);
				
				if( !empty($words[0]) ):
					$result = $words[0][0];

					if ( count( $words ) > 1 ) {
						$result .= $words[1][0];
					}

		            if( $option_value == "Vegan" || $option_value == "Vegetarian" ){
		            	$result_colour = strtolower($option_value);
		            	if ( $option_value == "Vegan" ) {
		            		$result .= "+";
		            	}
		            } else {
		            	$result_colour = strtolower($result);
		            }

					//if( in_array($result, $top_dietary) ):
		            ?>
		            	<span class="dietary-colour-<?php echo $result_colour; ?>" title="<?php echo $option_value; ?>"><?php echo $result; ?></span>
		            <?php 
					$count++;
		            //endif;
	        	endif;
	        	?>
	        <?php endif;?>
	    <?php endforeach;?>
	</div>
	<div class="product details product-item-details">
	
		<div class="product-detail-content">
        
            <?php $ct_attr = $this->getCustomAttribute(); ?>
            <?php if($ct_attr): ?>
                <?php $attribute_text = $_product->getAttributeText($ct_attr); ?>
                <div class="ct-attribute-text<?php if(!$attribute_text): ?> empty<?php endif ?>"><?php echo $attribute_text ?></div>
            <?php endif ?>
            
			
            
            
            
            <?php echo $this->getPrdPrice() ?>
			
            <?php echo $this->getSwatches(); ?>
		</div>
        
		<?php // Product Action ?>
		<div class="actions-link">
		
			<?php // Add to cart ?>
            <div class="actions-primary"<?php echo strpos($this->getPos(), 'grid-primary') ? "" : ''; ?>>
			
				<?php // Wishlist  ?>
			
				<button class="action towishlist"
				   data-title="<?php echo __('Add to Wish List') ?>"
				   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
				   data-post='<?php /* @escapeNotVerified */ echo $this->getWishListPost(); ?>'
				   data-action="add-to-wishlist"
				   role="button">
					<i class="pe-7s-like"></i>
				</button>
			
			
                <?php if ($_product->isSaleable()): ?>
                    <?php $postParams = $this->getPostParams(); ?>
                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                        <div class="field qty">
                            <span class="edit-qty minus disable-select-text" onclick="minusQty(this)">-</span>
                            <input type="number"
                            readonly
                            name="qty"
                            maxlength="12"
                            qty_inc="<?= $defaultQty ?>"
                            value="<?php /* @escapeNotVerified */ echo $defaultQty ?>"
                            title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" />
                            <span class="edit-qty plus disable-select-text" onclick="plusQty(this)">+</span>
                        </div>
					
                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                        <?php echo $this->getFk(); ?>
                        <button type="submit" data-title="<?php echo $block->escapeHtml(__('Add')); ?>" class="action tocart">
                            <span class="pe-7s-cart"></span>
                            <span class="text"><?php /* @escapeNotVerified */ echo __('Add') ?></span>
                        </button>
                    </form>
                <?php else: ?>
                    <button class="action tocart disabled" type="button" data-title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                        <span class="pe-7s-cart"></span>
                        <span class="text"><?php /* @escapeNotVerified */ echo __('Add') ?></span>
                    </button>
                <?php endif; ?>
            </div>
            <div class="inventory-info">
                <?php echo $blockStoreLocator->toHtml() ?>
            </div>
		</div>
	</div>
</div>