CLF output...
<br>
Order Increment Id: <?= $block->getData('orderIncrementId'); ?>
<br>
Shipping method: <?= $block->getData('shipping_method'); ?>
<br>
Shipping description: <?= $block->getData('shipping_description'); ?>
<br>
Clf user name: <?= $block->getData('clf_username'); ?>
<br>
Ws Endpoint: <?= $block->getData('ws_endpoint'); ?>
<br>
Authentication Token: <?= $block->getData('authenticationToken'); ?>
<br>
CLF order result: <?= $block->getData('clf_order_result'); ?>
<br>

<?= $block->getData('xml'); ?>
<br>

