<?php
/**
 * Copyright © Mageside. All rights reserved.
 * See MS-LICENSE.txt for license details.
 */
/**
 * @var Mageside\Recipe\Block\Frontend\Recipe\View $block
 */
$imageHelper = $this->helper(\Mageside\Recipe\Helper\Image::class);
$_writers = $block->getWriter();
?>
<div class="recipe-search">
    <div class="recipe-search_content">
        <form class="form" id="form-search">
            <div class="search">
                <div class="control">
                    <input name="search" type="text" class="input-text" autocomplete="off"
                           placeholder="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Search recipes')); ?>"/>
                    <input class="writer-url-key" type="hidden" name="writer" value="<?php echo $_writers->getWriterUrlKey(); ?>">
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                </button>
            </div>
        </form>
    </div>
</div>
<div class="writer-page-wrap recipes-page">
    <div class="writer-page-info"
        <?php if ($_writers->getWriterImage()) : ?>
        style='color: #040404; background-image: url("<?php echo $block->escapeHtml($block->getImageUrl() . '/' . $_writers->getWriterImage()); ?>")'
        <?php endif; ?>>
        <div class="writer-info__social-link">
            <ul>
                <?php if ($_writers->getYoutubeLink()) : ?>
                    <li>
                        <a href="<?php echo $block->escapeHtml($_writers->getYoutubeLink()); ?>" target="_blank">
                            <img src="<?php echo $block->escapeHtml($block->getViewFileUrl('Mageside_Recipe::images/recipe/icon-youtube.png')); ?>"
                                 title="Youtube" width="50" height="50"/>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($_writers->getFbLink()) : ?>
                    <li>
                        <a href="<?php echo $block->escapeHtml($_writers->getFbLink()); ?>" target="_blank">
                            <img src="<?php echo $block->escapeHtml($block->getViewFileUrl('Mageside_Recipe::images/recipe/icon-facebook.png')); ?>"
                                 title="Facebook" width="50" height="50"/>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($_writers->getInLink()) : ?>
                    <li>
                        <a href="<?php echo $block->escapeHtml($_writers->getInLink()); ?>" target="_blank">
                            <img src="<?php echo $block->escapeHtml($block->getViewFileUrl('Mageside_Recipe::images/recipe/icon-instagram.png')); ?>"
                                 title="Instagram" width="50" height="50"/>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($_writers->getSnapchatLink()) : ?>
                    <li>
                        <a href="<?php echo $block->escapeHtml($_writers->getSnapchatLink()); ?>" target="_blank">
                            <img src="<?php echo $block->escapeHtml($block->getViewFileUrl('Mageside_Recipe::images/recipe/icon-snapchat.png')); ?>"
                                 title="Snapchat" width="50" height="50"/>
                        </a>
                    </li>
                <?php endif; ?>
                <?php if ($_writers->getWebsiteLink()) : ?>
                    <li class="writer-website-title-link">
                        <a href="<?php echo $block->escapeHtml($_writers->getWebsiteLink()); ?>" target="_blank"><?php echo $block->escapeHtml(__('Visit my site')) ?></a>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
        <div class="writer-info__nickname" style="color: <?php echo $block->escapeHtml($_writers->getTextColor()); ?>">
            <?php echo $block->escapeHtml($_writers->getNickname()); ?>
        </div>
        <div class="writer-info__avatar">
            <?php if ($_writers->getAvatar()) : ?>
                <img src="<?php echo $block->escapeHtml($imageHelper->getResizedImage($block->getWriterAvatar(), 'recipe_guru_image')); ?>"
                     title="<?php echo $block->escapeHtml($_writers->getName()); ?>"
                     alt="<?php $block->escapeHtml(__('Writer Avatar')); ?>"
                     height="100"
                     width="100">
            <?php else : ?>
                <img src="<?php echo $block->escapeHtml($imageHelper->getResizedImage($block->getImageStub(), 'recipe_guru_image')); ?>"
                     alt="<?php $block->escapeHtml(__('Writer Avatar')); ?>" height="100" width="100">
            <?php endif; ?>
        </div>
        <div class="writer-info__about-writer" style="color: <?php echo $block->escapeHtml($_writers->getTextColor()); ?>">
            <?php echo $block->escapeHtml($_writers->getAboutWriter()); ?>
        </div>
    </div>
</div>
<input class="writer-url-key" type="hidden" value="<?php echo $block->escapeHtml($_writers->getWriterUrlKey()); ?>">
<div class="recipe-filters">
    <?php echo $block->getChildHtml('recipe_filters'); ?>
</div>

<div class="recipe-list-wrapper">
    <ul class="recipe-grid">
        <?php echo $block->getChildHtml('recipe_list'); ?>
    </ul>
</div>
<div class="recipe-list-wrapper" style="justify-content: center">
    <div class="more-recipes" style="text-align: center">
        <button id="update-recipes" class="action tocart primary action-allcart-primary">
            <span class="label"><?php echo $block->escapeHtml(__('See more recipes')); ?></span>
        </button>
    </div>
</div>