<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<?php
    $top_dietary = [ "Dairy Free", "Gluten Free", "Organic", "Raw", "Vegan", "Vegetarian", "Wheat Free", "Sugar Free", "Fair Trade", "Produce of GB" ];
?>
<ol class="items">
    
    <?php foreach ($filterItems as $filterItem) : ?>
        <?php
            if ( $filterItem->getFilter()->getName() == "Preferences" ) {
                $option_value = $filterItem->getLabel();
                if (!in_array($option_value, $top_dietary)) {
                    continue;
                }
            }
        ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0) : ?>
                <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">

                    <?php 
                    if ( $filterItem->getFilter()->getName() == "Preferences" ) : 
                    $option_value = $filterItem->getLabel();

                    $words = explode(' ', $filterItem->getLabel());  

                    $result = $words[0][0];

                    if ( count( $words ) > 1 ) {
                        $result .= $words[1][0];
                    }

                    if( $option_value == "Vegan" || $option_value == "Vegetarian" ){
                        $result_colour = strtolower($option_value);
                        if ( $option_value == "Vegan" ) {
                            $result .= "+";
                        }
                    } else {
                        $result_colour = strtolower($result);
                    }

                    ?>
                    <span class="dietary-colour dietary-colour-<?= $result_colour; ?>" title="<?php echo $option_value; ?>"><?= $result; ?></span>
                    <?php endif; ?>
                    <?= /* @noEscape */ $filterItem->getLabel() ?>
                    <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                        <!-- <span class="count"><?= /* @noEscape */ (int)$filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1) :
                                ?> <?= $block->escapeHtml(__('item')) ?><?php
                            else :
                                ?> <?= $block->escapeHtml(__('item')) ?><?php
                            endif;?></span></span> -->
                    <?php endif; ?>
                </a>
            <?php else :?>
                <?= /* @noEscape */ $filterItem->getLabel() ?>
                <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                    <span class="count"><?= /* @noEscape */ (int)$filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1) :
                            ?><?= $block->escapeHtml(__('items')) ?><?php
                        else :
                            ?><?= $block->escapeHtml(__('items')) ?><?php
                        endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
